name: M

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./node_modules/@jmlopez-rod/m/python
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: PATH setup
        run: |
          echo "./node_modules/@jmlopez-rod/m/bash/lib" >> $GITHUB_PATH
          pip install typing_extensions pycodestyle pylint mypy
      - name: Install Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
            version: 6.7.6
      - name: Install node packages
        run: pnpm install
      - name: Checks
        run: |
          ./build/build.sh
      - name: copy-workflow
        run: cp .github/workflows/madeup.yml .github/workflows/madeup2.yml

  docker-build:
    needs: build
    uses: ./.github/workflows/madeup.yml
    secrets: inherit
  
  docker-build2:
    needs: docker-build
    uses: ./.github/workflows/madeup2.yml
    secrets: inherit
